---
- name: Test managed Linux node
  hosts: all
  gather_facts: true

  tasks:

    - debug:
        msg: "Hostname: {{ ansible_hostname }}"

    - debug:
        msg: "FQDN: {{ ansible_fqdn }}"

    - debug:
        msg: "Sistema Operativo: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - debug:
        msg: "Kernel: {{ ansible_kernel }}"

    - debug:
        msg: "Arquitectura: {{ ansible_architecture }}"

    - debug:
        msg: "IP Principal: {{ ansible_default_ipv4.address }}"
